### ISSUE TITLE
Functional requirements for hardware interface

### ISSUE THREAD

**Issue by GwnDaan** [ad3154/Isobus-plus-plus#166]
I was trying to fix a lot of the issues from SonarCloud for the CANHardwareInterface class file but got a bit lost when trying to fix the larger functions mostly the threaded ones. So I'm switching to a bit more TDD approach for them I think. I propose we need to be able to do/test for in the hardware interface:

- [x] Start with #182 
- [x] Implementation of the isobus::send_can_message_frame_to_hardware
- [x] Implementation of the isobus::receive_can_message_frame_from_hardware
- [x] Function to add/remove/removeAll frame handler(s)
- [x] Function to add/remove/removeAll canFrame(s) to/from the rx queue
- [x] Function to add/remove/removeAll listener(s) for message received events
- [x] Function to add/remove/removeAll listener(s) for message sent events (as utility for applications)
- [x] Function to add/remove/removeAll listener(s) for update events
- [x] Function to set/get periodic update time 

Out of curiosity, why did we choose to make it a requirement that the frame handlers are added before the interface is started? Maybe for performance benefits?

I was also thinking that we could make a direct call to for example a `isobus::receive_can_message_from_hardware` function instead of the "raw can glue" we have now? With the listeners the application still has the ability to listen for messages in both directions, but they wont be able to break anything I guess. Same for making direct call to the `isobus::CANNetwork.update()` function. Though I see there could be weird behavior when they also call the update from within their own listener, hmm... I guess that's why it's the way it is now.

**Comment by ad3154** [comment]
Time for another info dump from early development, haha!

Some of the reasons why the CAN hardware interface is like that are obsolete now. Initially I wanted the hardware interface to be completely optional, and removable so that the stack's main guts could be run on systems that didn't support std::thread and std::mutex but then those types ended up in the main stack anyways, so now that doesn't really matter that much... One reason it doesn't call `isobus::receive_can_message_from_hardware` directly was to prevent a circular dependency, which also doesn't really matter now, as we include the logger in the hardware layer.  Essentially the two layers have really become intertwined with more of the separation of duties happening at the plugin layer now instead of between the stack and the hardware interface instead of my original vision. This is fine I think as it's still very portable and hardware independent, so if we want to rework it a little to make it nicer with those thoughts out of the way that is A-OK with me.
