### ISSUE TITLE
Increase readability when using variables in log messages

### ISSUE THREAD

**Issue by GwnDaan** [ad3154/Isobus-plus-plus#222]
**Is your feature request related to a problem? Please describe.**
Currently a lot of 'inbetween' formatting is necessary to get a running sentence. For example:
https://github.com/ad3154/Isobus-plus-plus/blob/44a2941ca23f50f0a7ed07b4f74b460c91db0815/isobus/src/isobus_task_controller_client.cpp#L839-L847
I find this quite a bit harder to read than using formatting specifiers, and therefore also harder to maintain.

**Describe the solution you'd like**
A possibility would be to use the built-in `std::snprintf` to format messages. The same example from above would then look similar to:
```cpp
CANStackLogger::debug("[TC]: TC Server supports version %uh with %uh booms, %uh sections, and %uh position based control channels.",
                      messageData[1], messageData[5], messageData[6], messageData[7]);
```
Though one downside would be that confusion may arise when figuring out which variables belongs to which specifier. But I feel like a more readable sentence outweighs that.

**Additional information**
I found an example on [stackoverflow](https://stackoverflow.com/a/26221725) while gathering information that could be useful:
```c++
#include <memory>
#include <string>
#include <stdexcept>

template<typename ... Args>
std::string string_format( const std::string& format, Args ... args )
{
    int size_s = std::snprintf( nullptr, 0, format.c_str(), args ... ) + 1; // Extra space for '\0'
    if( size_s <= 0 ){ throw std::runtime_error( "Error during formatting." ); }
    auto size = static_cast<size_t>( size_s );
    std::unique_ptr<char[]> buf( new char[ size ] );
    std::snprintf( buf.get(), size, format.c_str(), args ... );
    return std::string( buf.get(), buf.get() + size - 1 ); // We don't want the '\0' inside
}
```

The code snippet above is licensed under [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by ad3154** [comment]
I also think our logging messages are a bit crunchy. Like, `spdlog` does it like this, which I really like: `spdlog::warn("Text {} and {}", value1, value2);` but uses C++ 20 I think to make that happen.

I worry a bit about using snprintf and things like it, since they rely on developer diligence to not cause overflows. Sonar may flag it as a security risk (and rightly so). So if there's alternate, safer ways to do it, that'd be nice. I also don't love the idea proposed by that `string_format` for a number of reasons...

Perhaps we could come up with some wrapper using string streams or something...? Like a recursive variadic function?
