### ISSUE TITLE
examples nmea200 not work in esp-idf

### ISSUE THREAD

**Issue by orcim** [ad3154/Isobus-plus-plus#245]
The example transport_layer In Socket "vcan0" under Linux and under Edp-idf works .
The example NMEA2000 stops after Address Claim ?  Both under Linux and under Esp-idf.

Any suggestions? 
Thank you.

Esp-Idf (dump)
===========
twai 18eafffe [3] 00 ee 00
twai 18eeff1c [8] 02 00 00 08 00 10 00 a0

**Comment by ad3154** [comment]
This seems like it is the same thing we saw in #61 where similar to TP and ETP back then, fast packet is being optimized out by your linker when linking the library as a static library. We'll have to update the network manager to contain the instance of the protocol instead of having it be a static instance. This will mean we'll have to update the example a bit as well, but shouldn't be too bad. I'll try and get started on a fix for this.
